### ISSUE TITLE
SSX_nexus fails

### ISSUE THREAD

**Issue by ndevenish** [dials/nexgen#127]
v0.6.28, latest

possibly not intended to run this but am bumping round in the dark trying to work out how to fix something and bumped into this

```
 % SSX_nexus
Traceback (most recent call last):
  File "/dls/science/users/mep23677/dist/conda_base/bin/SSX_nexus", line 5, in <module>
    from nexgen.command_line.SSX_cli import main
  File "/dls/science/users/mep23677/dist/modules/nexgen/src/nexgen/command_line/SSX_cli.py", line 10, in <module>
    from .. import P, log
ImportError: cannot import name 'P' from 'nexgen' (/dls/science/users/mep23677/dist/modules/nexgen/src/nexgen/__init__.py)
```

**Comment by noemifrisina** [comment]
Good spot, an import was forgotten in the refactoring insanity. Fix in #130.
